//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveConsole.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_FR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_FR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EasySaveConsole.Properties.Resources_FR", typeof(Resources_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string change_lang {
            get {
                return ResourceManager.GetString("change_lang", resourceCulture);
            }
        }
        
        internal static string change_lang_en {
            get {
                return ResourceManager.GetString("change_lang_en", resourceCulture);
            }
        }
        
        internal static string change_lang_fr {
            get {
                return ResourceManager.GetString("change_lang_fr", resourceCulture);
            }
        }
        
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        internal static string confirm_execute_all_saving_job {
            get {
                return ResourceManager.GetString("confirm_execute_all_saving_job", resourceCulture);
            }
        }
        
        internal static string create_saving_job {
            get {
                return ResourceManager.GetString("create_saving_job", resourceCulture);
            }
        }
        
        internal static string delete_saving_job {
            get {
                return ResourceManager.GetString("delete_saving_job", resourceCulture);
            }
        }
        
        internal static string enter_destination_path {
            get {
                return ResourceManager.GetString("enter_destination_path", resourceCulture);
            }
        }
        
        internal static string enter_nameSave {
            get {
                return ResourceManager.GetString("enter_nameSave", resourceCulture);
            }
        }
        
        internal static string enter_job_name {
            get {
                return ResourceManager.GetString("enter_job_name", resourceCulture);
            }
        }
        
        internal static string enter_job_type {
            get {
                return ResourceManager.GetString("enter_job_type", resourceCulture);
            }
        }
        
        internal static string enter_source_path {
            get {
                return ResourceManager.GetString("enter_source_path", resourceCulture);
            }
        }
        
        internal static string execute_all_saving_job {
            get {
                return ResourceManager.GetString("execute_all_saving_job", resourceCulture);
            }
        }
        
        internal static string execute_one_saving_job {
            get {
                return ResourceManager.GetString("execute_one_saving_job", resourceCulture);
            }
        }
        
        internal static string execute_saving_job {
            get {
                return ResourceManager.GetString("execute_saving_job", resourceCulture);
            }
        }
        
        internal static string impossible_create_saving_job {
            get {
                return ResourceManager.GetString("impossible_create_saving_job", resourceCulture);
            }
        }
        
        internal static string leave_current_menu {
            get {
                return ResourceManager.GetString("leave_current_menu", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string change_log_format {
            get {
                return ResourceManager.GetString("show_info", resourceCulture);
            }
        }
        
        internal static string xml_log_format {
            get {
                return ResourceManager.GetString("show_log", resourceCulture);
            }
        }
        
        internal static string show_saving_jobs {
            get {
                return ResourceManager.GetString("show_state", resourceCulture);
            }
        }
        
        internal static string title_main_menu {
            get {
                return ResourceManager.GetString("title_main_menu", resourceCulture);
            }
        }
        
        internal static string user_input_error {
            get {
                return ResourceManager.GetString("user_input_error", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string error_directory_path {
            get {
                return ResourceManager.GetString("error_directory_path", resourceCulture);
            }
        }
        
        internal static string file_transfered {
            get {
                return ResourceManager.GetString("file_transfered", resourceCulture);
            }
        }
        
        internal static string perm_error {
            get {
                return ResourceManager.GetString("perm_error", resourceCulture);
            }
        }
    }
}
