//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        internal static string change_lang {
            get {
                return ResourceManager.GetString("change_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string change_lang_en {
            get {
                return ResourceManager.GetString("change_lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français .
        /// </summary>
        internal static string change_lang_fr {
            get {
                return ResourceManager.GetString("change_lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete it?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to execute all backup?.
        /// </summary>
        internal static string confirm_execute_all_saving_job {
            get {
                return ResourceManager.GetString("confirm_execute_all_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a saving job.
        /// </summary>
        internal static string create_saving_job {
            get {
                return ResourceManager.GetString("create_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a saving job.
        /// </summary>
        internal static string delete_saving_job {
            get {
                return ResourceManager.GetString("delete_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the destination of the source file:.
        /// </summary>
        internal static string enter_destination_path {
            get {
                return ResourceManager.GetString("enter_destination_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name for the saving job:.
        /// </summary>
        internal static string enter_job_name {
            get {
                return ResourceManager.GetString("enter_job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the type of backup (c|d):.
        /// </summary>
        internal static string enter_job_type {
            get {
                return ResourceManager.GetString("enter_job_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the path of the source file:.
        /// </summary>
        internal static string enter_source_path {
            get {
                return ResourceManager.GetString("enter_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all saving job.
        /// </summary>
        internal static string execute_all_saving_job {
            get {
                return ResourceManager.GetString("execute_all_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute only one saving job.
        /// </summary>
        internal static string execute_one_saving_job {
            get {
                return ResourceManager.GetString("execute_one_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a saving job.
        /// </summary>
        internal static string execute_saving_job {
            get {
                return ResourceManager.GetString("execute_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have 5 existing saving jobs, you can not add more.
        /// </summary>
        internal static string impossible_create_saving_job {
            get {
                return ResourceManager.GetString("impossible_create_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave .
        /// </summary>
        internal static string leave_current_menu {
            get {
                return ResourceManager.GetString("leave_current_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving Jobs list:.
        /// </summary>
        internal static string list_jobs {
            get {
                return ResourceManager.GetString("list_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logbook.
        /// </summary>
        internal static string show_info {
            get {
                return ResourceManager.GetString("show_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show saving jobs.
        /// </summary>
        internal static string show_job {
            get {
                return ResourceManager.GetString("show_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show logs.
        /// </summary>
        internal static string show_log {
            get {
                return ResourceManager.GetString("show_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show backup status.
        /// </summary>
        internal static string show_state {
            get {
                return ResourceManager.GetString("show_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Menu.
        /// </summary>
        internal static string title_main_menu {
            get {
                return ResourceManager.GetString("title_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : invalid input.
        /// </summary>
        internal static string user_input_error {
            get {
                return ResourceManager.GetString("user_input_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
