//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveConsole.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_FR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_FR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EasySaveConsole.Properties.Resources_FR", typeof(Resources_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string change_lang {
            get {
                return ResourceManager.GetString("change_lang", resourceCulture);
            }
        }
        
        public static string change_lang_en {
            get {
                return ResourceManager.GetString("change_lang_en", resourceCulture);
            }
        }
        
        public static string change_lang_fr {
            get {
                return ResourceManager.GetString("change_lang_fr", resourceCulture);
            }
        }
        
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        public static string confirm_execute_all_saving_job {
            get {
                return ResourceManager.GetString("confirm_execute_all_saving_job", resourceCulture);
            }
        }
        
        public static string create_saving_job {
            get {
                return ResourceManager.GetString("create_saving_job", resourceCulture);
            }
        }
        
        public static string delete_saving_job {
            get {
                return ResourceManager.GetString("delete_saving_job", resourceCulture);
            }
        }
        
        public static string enter_destination_path {
            get {
                return ResourceManager.GetString("enter_destination_path", resourceCulture);
            }
        }
        
        public static string enter_nameSave {
            get {
                return ResourceManager.GetString("enter_nameSave", resourceCulture);
            }
        }
        
        public static string enter_job_name {
            get {
                return ResourceManager.GetString("enter_job_name", resourceCulture);
            }
        }
        
        public static string enter_job_type {
            get {
                return ResourceManager.GetString("enter_job_type", resourceCulture);
            }
        }
        
        public static string enter_source_path {
            get {
                return ResourceManager.GetString("enter_source_path", resourceCulture);
            }
        }
        
        public static string execute_all_saving_job {
            get {
                return ResourceManager.GetString("execute_all_saving_job", resourceCulture);
            }
        }
        
        public static string execute_one_saving_job {
            get {
                return ResourceManager.GetString("execute_one_saving_job", resourceCulture);
            }
        }
        
        public static string execute_saving_job {
            get {
                return ResourceManager.GetString("execute_saving_job", resourceCulture);
            }
        }
        
        public static string impossible_create_saving_job {
            get {
                return ResourceManager.GetString("impossible_create_saving_job", resourceCulture);
            }
        }
        
        public static string leave_current_menu {
            get {
                return ResourceManager.GetString("leave_current_menu", resourceCulture);
            }
        }
        
        public static string list_jobs {
            get {
                return ResourceManager.GetString("list_jobs", resourceCulture);
            }
        }
        
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        public static string change_log_format {
            get {
                return ResourceManager.GetString("change_log_format", resourceCulture);
            }
        }
        
        public static string json_log_format {
            get {
                return ResourceManager.GetString("json_log_format", resourceCulture);
            }
        }
        
        public static string xml_log_format {
            get {
                return ResourceManager.GetString("xml_log_format", resourceCulture);
            }
        }
        
        public static string show_saving_jobs {
            get {
                return ResourceManager.GetString("show_saving_jobs", resourceCulture);
            }
        }
        
        public static string title_main_menu {
            get {
                return ResourceManager.GetString("title_main_menu", resourceCulture);
            }
        }
        
        public static string user_input_error {
            get {
                return ResourceManager.GetString("user_input_error", resourceCulture);
            }
        }
        
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        public static string error_directory_path {
            get {
                return ResourceManager.GetString("error_directory_path", resourceCulture);
            }
        }
        
        public static string file_transfered {
            get {
                return ResourceManager.GetString("file_transfered", resourceCulture);
            }
        }
        
        public static string perm_error {
            get {
                return ResourceManager.GetString("perm_error", resourceCulture);
            }
        }
        
        public static string log_file_path {
            get {
                return ResourceManager.GetString("log_file_path", resourceCulture);
            }
        }
        
        public static string no_saving_job {
            get {
                return ResourceManager.GetString("no_saving_job", resourceCulture);
            }
        }
        
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        public static string decrypt {
            get {
                return ResourceManager.GetString("decrypt", resourceCulture);
            }
        }
        
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        public static string diferential {
            get {
                return ResourceManager.GetString("diferential", resourceCulture);
            }
        }
        
        public static string logs {
            get {
                return ResourceManager.GetString("logs", resourceCulture);
            }
        }
        
        public static string select_all {
            get {
                return ResourceManager.GetString("select_all", resourceCulture);
            }
        }
        
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        public static string cryptosoft_choice {
            get {
                return ResourceManager.GetString("cryptosoft_choice", resourceCulture);
            }
        }
        
        public static string password_placeholder {
            get {
                return ResourceManager.GetString("password_placeholder", resourceCulture);
            }
        }
    }
}
