//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string change_lang {
            get {
                return ResourceManager.GetString("change_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string change_lang_en {
            get {
                return ResourceManager.GetString("change_lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français .
        /// </summary>
        public static string change_lang_fr {
            get {
                return ResourceManager.GetString("change_lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete it?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to execute all backup?.
        /// </summary>
        public static string confirm_execute_all_saving_job {
            get {
                return ResourceManager.GetString("confirm_execute_all_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a saving job.
        /// </summary>
        public static string create_saving_job {
            get {
                return ResourceManager.GetString("create_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrypt.
        /// </summary>
        public static string decrypt {
            get {
                return ResourceManager.GetString("decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a saving job.
        /// </summary>
        public static string delete_saving_job {
            get {
                return ResourceManager.GetString("delete_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à diferential.
        /// </summary>
        public static string diferential {
            get {
                return ResourceManager.GetString("diferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the destination of the source file:.
        /// </summary>
        public static string enter_destination_path {
            get {
                return ResourceManager.GetString("enter_destination_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name for the saving job:.
        /// </summary>
        public static string enter_job_name {
            get {
                return ResourceManager.GetString("enter_job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the type of backup (c|d):.
        /// </summary>
        public static string enter_job_type {
            get {
                return ResourceManager.GetString("enter_job_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the path of the destination file:.
        /// </summary>
        public static string enter_source_path {
            get {
                return ResourceManager.GetString("enter_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The destination or source directory doesn&apos;t exists..
        /// </summary>
        public static string error_directory_path {
            get {
                return ResourceManager.GetString("error_directory_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all saving job.
        /// </summary>
        public static string execute_all_saving_job {
            get {
                return ResourceManager.GetString("execute_all_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute only one saving job.
        /// </summary>
        public static string execute_one_saving_job {
            get {
                return ResourceManager.GetString("execute_one_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a saving job.
        /// </summary>
        public static string execute_saving_job {
            get {
                return ResourceManager.GetString("execute_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File transfered : .
        /// </summary>
        public static string file_transfered {
            get {
                return ResourceManager.GetString("file_transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have 5 existing saving jobs, you can not add more.
        /// </summary>
        public static string impossible_create_saving_job {
            get {
                return ResourceManager.GetString("impossible_create_saving_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave .
        /// </summary>
        public static string leave_current_menu {
            get {
                return ResourceManager.GetString("leave_current_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving Jobs list:.
        /// </summary>
        public static string list_jobs {
            get {
                return ResourceManager.GetString("list_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string logs {
            get {
                return ResourceManager.GetString("logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permsission Error
        ///
        ///.
        /// </summary>
        public static string perm_error {
            get {
                return ResourceManager.GetString("perm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All .
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logbook.
        /// </summary>
        public static string show_info {
            get {
                return ResourceManager.GetString("show_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show saving jobs.
        /// </summary>
        public static string show_job {
            get {
                return ResourceManager.GetString("show_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show logs.
        /// </summary>
        public static string show_log {
            get {
                return ResourceManager.GetString("show_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show backup status.
        /// </summary>
        public static string show_state {
            get {
                return ResourceManager.GetString("show_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Menu.
        /// </summary>
        public static string title_main_menu {
            get {
                return ResourceManager.GetString("title_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : invalid input.
        /// </summary>
        public static string user_input_error {
            get {
                return ResourceManager.GetString("user_input_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
